import '@styles/tailwind.css'
import { Space_Grotesk } from 'next/font/google'
import Navbar from 'components/Navbar'

export const metadata = {
  title: 'E-commerce',
  description: 'Generated by Next.js',
}

const space_Grotesk = Space_Grotesk({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={space_Grotesk.className} >
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
